name: PR

on:
  pull_request:
    branches:
    - main

jobs:
  verify:
    name: Verify (${{ matrix.directory }})
    uses: unfunco/meta/.github/workflows/verify-terraform.yaml@8a2e3873c609d86b9a67b353a9111bd44171240d # v0.3.0
    with:
      terraform-version-file: .terraform-version
      working-directory: ${{ matrix.directory }}
    strategy:
      fail-fast: false
      matrix:
        directory:
        - .
        - modules/ci-iam-policy
